name: eShopOnWeb Build and Test

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  DOTNET_APP_DIR: ~/publish
  RESOURCE-GROUP: rg-eshoponweb-phantom
  LOCATION: eastus
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 762c3eb0-1001-4aa6-84eb-61560b197532
  WEBAPP-NAME: eshoponweb-webapp-phantom-06-app

jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: self-hosted
    steps:
      #checkout the repository
      - uses: actions/checkout@v5
      #prepare runner for desired .net version SDK

      #Build/Test/Publish the .net project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_APP_DIR}}/myapp
          cd ${{env.DOTNET_APP_DIR}}/myapp
          zip -r ../app.zip .
      # upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v5
        with:
          name: .net-app
          path: ${{env.DOTNET_APP_DIR}}/app.zip

      # upload the bicep template as artifacts for next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v5
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + Publish webapp
  deploy:
    runs-on: self-hosted
    needs: buildandtest
    environment:
      name: "Development"
    steps:
      #Download the publish files created in previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v6
        with:
          name: .net-app
          path: .net-app

      #Download the bicep templates from previous job
      - name: Download artifact from build job
        uses: actions/download-artifact@v6
        with:
          name: bicep-template
          path: bicep-template

      #Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using Bicep file
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      # Publish website to Azure App Service (WebApp)
      # Step disabled due to issue where the site sometimes can't be found: https://github.com/microsoft/pipelines-appservice-lib/issues/56. Instead deploy using CLI
      - name: Publish Website to WebApp
        if: false #Disable step due to comment above
        uses: Azure/webapps-deploy@v3
        with:
          type: ZIP
          app-name: ${{ env.WEBAPP-NAME  }}
          package: .net-app/app.zip

      # Publish website to Azure App Service using CLI (WebApp)
      - name: Publish Website to WebApp
        run: az webapp deploy \
          --name ${{ env.WEBAPP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --src-path ~/publish/app.zip \
          --type zip
        
